#
# To deploy:
#
# kubectl apply -f scripts/deploy.yaml
#
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-streaming
  template:
    metadata:
      labels:
        app: video-streaming
    spec:
      containers: 
      - name: video-streaming
        image: australia-southeast2-docker.pkg.dev/sit722-10-2-hd/s224021028gcr/video-streaming:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "4000"
        - name: RABBIT
          value: amqp://test:test@rabbit:5672
---
apiVersion: v1
kind: Service
metadata:
  name: video-streaming
spec:
  selector:
    app: video-streaming
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
