pipeline {
    agent any
    environment {
        USE_GKE_GCLOUD_AUTH_PLUGIN = "True"
        GCP_PROJECT = "sit722-10-2-hd"
        REGION = "australia-southeast2-a"
        CLUSTER_NAME = "cluster-1"
    }
    stages {
        stage("Login to Google Cloud") {
            steps {
                withCredentials([file(credentialsId: "ea148254-95f9-4aec-b8b4-2fa0dc449d50", variable: "GOOGLE_APPLICATION_CREDENTIALS")]) {
                    bat "gcloud auth activate-service-account --key-file=${GOOGLE_APPLICATION_CREDENTIALS}"
                    bat "gcloud config set project ${GCP_PROJECT}"
                }
            }
        }
        stage("Configure kubectl for GKE") {
            steps {
                bat "gcloud container clusters get-credentials ${CLUSTER_NAME} --region ${REGION} --project ${GCP_PROJECT}"
            }
        }
        stage("Deploy infrastructure to GKE - MongoDB") {
            steps {
                bat "kubectl apply -f scripts/cd/mongodb.yaml"
            }
        }
        stage("Deploy infrastructure to GKE - RabbitMQ") {
            steps {
                bat "kubectl apply -f scripts/cd/rabbit.yaml"
            }
        }
    }
}
